### ISSUE TITLE
cudaErrorInvalidConfiguration

### ISSUE THREAD

**Issue by a312863063** [naver-ai/ZIM#11]
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'/mask_decoder/fusion_blks.2/Concat' Status
 Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

Has anyone encountered this issue and how did you resolve it? Thanks!

**Comment by a312863063** [comment]
This error occurred while using the ZimAutomaticMaskGenerator for inference. However, when switching to ZimPredictor for inference, the problem disappeared, and everything worked fine (in GPU mode). My machine is equipped with a 4090 GPU, CUDA 12.4, and onnxruntime-gpu 1.20.1.
<b>Use ZimPredictor in GPU mode, while ZimAutomaticMaskGenerator can be used in CPU mode.</b>
